# Generated by Django 2.2.1 on 2019-11-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_user_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
    ]
