# Generated by Django 2.2.1 on 2019-11-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20191106_2107'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='publish',
            table='publish',
        ),
    ]
