# Generated by Django 2.2.1 on 2019-11-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_book_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('birthday', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
