# Generated by Django 2.2.1 on 2019-11-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')])),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
